---

- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"
  tags: [ 'ntp' ]

- name: Install the required packages
  package: name={{ item }} state=present
  with_items: ntp_pkgs
  tags: [ 'ntp' ]

- name: Copy the ntp.conf template file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
   - restart ntp
  tags: [ 'ntp' ]
